/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.view;

import br.com.modelo.controller.MarcaController;
import br.com.modelo.negocio.Marca;

/**
 *
 * @author isequiel_borges
 */
public class AtualizarMarca extends javax.swing.JFrame {
     MarcaTableModel modelo;
     int linhaSelecionada;
     
    /**
     * Creates new form AtualizarMarca
     */
    public AtualizarMarca(int linhaSelecionada, int idMarca, MarcaTableModel modelo) {
        this.linhaSelecionada = linhaSelecionada;
        this.modelo = modelo;
        initComponents();
        
        Marca m = new Marca();
        MarcaController mc = new MarcaController();
        m = mc.getMarcaById(idMarca);
        txId.setText((Integer.toString(m.getId())));
        txMarca.setText(m.getNome());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txId = new javax.swing.JTextField();
        txMarca = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(500, 350));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Wide Latin", 3, 24)); // NOI18N
        jLabel1.setText("Atualizar Marca");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 19, 390, 40);

        jLabel2.setText("Id:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 100, 14, 14);

        jLabel3.setText("Nome:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 140, 40, 14);
        getContentPane().add(txId);
        txId.setBounds(60, 90, 290, 30);
        getContentPane().add(txMarca);
        txMarca.setBounds(60, 130, 290, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setText("Limpar");
        getContentPane().add(jButton1);
        jButton1.setBounds(263, 250, 80, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton2.setText("Salvar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(350, 250, 90, 30);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 510, 320);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       Marca m = new Marca();
       m.setId((Integer.parseInt(txId.getText())));
       m.setNome(txMarca.getText());
       
       MarcaController mc = new MarcaController();
       mc.atualizar(m);
       
       modelo.updateMarca(linhaSelecionada, m);
       dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txId;
    private javax.swing.JTextField txMarca;
    // End of variables declaration//GEN-END:variables
}
