/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.view;

/**
 *
 * @author isequiel_borges
 */
public class JanelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JanelaPrincipal
     */
    public JanelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        botaoMarca = new javax.swing.JButton();
        botaoModelo = new javax.swing.JButton();
        botaoAutomovel = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        jSeparator15 = new javax.swing.JSeparator();
        jSeparator16 = new javax.swing.JSeparator();
        jSeparator17 = new javax.swing.JSeparator();
        jSeparator18 = new javax.swing.JSeparator();
        jSeparator19 = new javax.swing.JSeparator();
        jSeparator20 = new javax.swing.JSeparator();
        jSeparator21 = new javax.swing.JSeparator();
        jSeparator22 = new javax.swing.JSeparator();
        jSeparator23 = new javax.swing.JSeparator();
        jSeparator24 = new javax.swing.JSeparator();
        jSeparator25 = new javax.swing.JSeparator();
        jSeparator26 = new javax.swing.JSeparator();
        jSeparator27 = new javax.swing.JSeparator();
        jSeparator28 = new javax.swing.JSeparator();
        jSeparator29 = new javax.swing.JSeparator();
        jSeparator30 = new javax.swing.JSeparator();
        jSeparator31 = new javax.swing.JSeparator();
        jSeparator32 = new javax.swing.JSeparator();
        jSeparator33 = new javax.swing.JSeparator();
        jSeparator34 = new javax.swing.JSeparator();
        jSeparator35 = new javax.swing.JSeparator();
        jSeparator36 = new javax.swing.JSeparator();
        jSeparator37 = new javax.swing.JSeparator();
        jSeparator38 = new javax.swing.JSeparator();
        jSeparator39 = new javax.swing.JSeparator();
        jSeparator40 = new javax.swing.JSeparator();
        jSeparator41 = new javax.swing.JSeparator();
        jSeparator42 = new javax.swing.JSeparator();
        jSeparator43 = new javax.swing.JSeparator();
        jSeparator44 = new javax.swing.JSeparator();
        jSeparator45 = new javax.swing.JSeparator();
        jSeparator46 = new javax.swing.JSeparator();
        jSeparator47 = new javax.swing.JSeparator();
        jSeparator48 = new javax.swing.JSeparator();
        jSeparator49 = new javax.swing.JSeparator();
        jSeparator50 = new javax.swing.JSeparator();
        jSeparator51 = new javax.swing.JSeparator();
        jSeparator52 = new javax.swing.JSeparator();
        jSeparator53 = new javax.swing.JSeparator();
        jSeparator54 = new javax.swing.JSeparator();
        jSeparator55 = new javax.swing.JSeparator();
        jSeparator56 = new javax.swing.JSeparator();
        jSeparator57 = new javax.swing.JSeparator();
        jSeparator58 = new javax.swing.JSeparator();
        jSeparator59 = new javax.swing.JSeparator();
        jSeparator60 = new javax.swing.JSeparator();
        jSeparator61 = new javax.swing.JSeparator();
        jSeparator62 = new javax.swing.JSeparator();
        jSeparator63 = new javax.swing.JSeparator();
        jSeparator64 = new javax.swing.JSeparator();
        jSeparator65 = new javax.swing.JSeparator();
        jSeparator66 = new javax.swing.JSeparator();
        jSeparator67 = new javax.swing.JSeparator();
        jSeparator68 = new javax.swing.JSeparator();
        jSeparator69 = new javax.swing.JSeparator();
        jSeparator70 = new javax.swing.JSeparator();
        jSeparator71 = new javax.swing.JSeparator();
        jSeparator72 = new javax.swing.JSeparator();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        botaoMarca.setBackground(new java.awt.Color(255, 255, 255));
        botaoMarca.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botaoMarca.setText("Marca");
        botaoMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMarcaActionPerformed(evt);
            }
        });
        jPanel1.add(botaoMarca);
        botaoMarca.setBounds(270, 150, 120, 30);

        botaoModelo.setBackground(new java.awt.Color(255, 255, 255));
        botaoModelo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botaoModelo.setText("Modelo");
        botaoModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoModeloActionPerformed(evt);
            }
        });
        jPanel1.add(botaoModelo);
        botaoModelo.setBounds(270, 210, 120, 30);

        botaoAutomovel.setBackground(new java.awt.Color(255, 255, 255));
        botaoAutomovel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botaoAutomovel.setText("Automóvel");
        jPanel1.add(botaoAutomovel);
        botaoAutomovel.setBounds(270, 270, 120, 30);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Wide Latin", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Principal");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(190, 10, 250, 25);

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel4);
        jPanel4.setBounds(640, -30, 10, 460);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(40, 30, 610, 40);

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(40, 390, 610, 40);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(600, 90, 50, 20);
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(600, 80, 50, 20);
        jPanel1.add(jSeparator3);
        jSeparator3.setBounds(600, 120, 50, 20);
        jPanel1.add(jSeparator4);
        jSeparator4.setBounds(600, 100, 50, 20);
        jPanel1.add(jSeparator5);
        jSeparator5.setBounds(600, 110, 50, 20);
        jPanel1.add(jSeparator6);
        jSeparator6.setBounds(600, 120, 50, 20);
        jPanel1.add(jSeparator7);
        jSeparator7.setBounds(600, 120, 50, 20);
        jPanel1.add(jSeparator8);
        jSeparator8.setBounds(600, 130, 50, 20);
        jPanel1.add(jSeparator9);
        jSeparator9.setBounds(600, 140, 50, 20);
        jPanel1.add(jSeparator10);
        jSeparator10.setBounds(600, 150, 50, 20);
        jPanel1.add(jSeparator11);
        jSeparator11.setBounds(600, 160, 50, 20);
        jPanel1.add(jSeparator12);
        jSeparator12.setBounds(40, 380, 50, 20);
        jPanel1.add(jSeparator13);
        jSeparator13.setBounds(600, 150, 50, 20);
        jPanel1.add(jSeparator14);
        jSeparator14.setBounds(600, 170, 50, 20);
        jPanel1.add(jSeparator15);
        jSeparator15.setBounds(600, 170, 50, 20);
        jPanel1.add(jSeparator16);
        jSeparator16.setBounds(600, 170, 50, 20);
        jPanel1.add(jSeparator17);
        jSeparator17.setBounds(600, 180, 50, 20);
        jPanel1.add(jSeparator18);
        jSeparator18.setBounds(600, 190, 50, 20);
        jPanel1.add(jSeparator19);
        jSeparator19.setBounds(600, 200, 50, 20);
        jPanel1.add(jSeparator20);
        jSeparator20.setBounds(600, 210, 50, 20);
        jPanel1.add(jSeparator21);
        jSeparator21.setBounds(600, 220, 50, 20);
        jPanel1.add(jSeparator22);
        jSeparator22.setBounds(600, 230, 50, 20);
        jPanel1.add(jSeparator23);
        jSeparator23.setBounds(600, 240, 50, 20);
        jPanel1.add(jSeparator24);
        jSeparator24.setBounds(600, 250, 50, 20);
        jPanel1.add(jSeparator25);
        jSeparator25.setBounds(600, 270, 50, 10);
        jPanel1.add(jSeparator26);
        jSeparator26.setBounds(600, 260, 50, 20);
        jPanel1.add(jSeparator27);
        jSeparator27.setBounds(600, 280, 50, 20);
        jPanel1.add(jSeparator28);
        jSeparator28.setBounds(600, 290, 50, 20);
        jPanel1.add(jSeparator29);
        jSeparator29.setBounds(600, 300, 50, 20);
        jPanel1.add(jSeparator30);
        jSeparator30.setBounds(600, 310, 50, 20);
        jPanel1.add(jSeparator31);
        jSeparator31.setBounds(600, 320, 50, 20);
        jPanel1.add(jSeparator32);
        jSeparator32.setBounds(600, 330, 50, 20);
        jPanel1.add(jSeparator33);
        jSeparator33.setBounds(600, 340, 50, 20);
        jPanel1.add(jSeparator34);
        jSeparator34.setBounds(600, 360, 50, 10);
        jPanel1.add(jSeparator35);
        jSeparator35.setBounds(600, 350, 50, 20);
        jPanel1.add(jSeparator36);
        jSeparator36.setBounds(600, 360, 50, 20);
        jPanel1.add(jSeparator37);
        jSeparator37.setBounds(600, 370, 50, 20);
        jPanel1.add(jSeparator38);
        jSeparator38.setBounds(600, 380, 50, 20);
        jPanel1.add(jSeparator39);
        jSeparator39.setBounds(600, 380, 50, 20);
        jPanel1.add(jSeparator40);
        jSeparator40.setBounds(40, 80, 50, 20);
        jPanel1.add(jSeparator41);
        jSeparator41.setBounds(40, 90, 50, 20);
        jPanel1.add(jSeparator42);
        jSeparator42.setBounds(40, 100, 50, 20);
        jPanel1.add(jSeparator43);
        jSeparator43.setBounds(40, 110, 50, 20);
        jPanel1.add(jSeparator44);
        jSeparator44.setBounds(40, 110, 50, 20);
        jPanel1.add(jSeparator45);
        jSeparator45.setBounds(40, 120, 50, 20);
        jPanel1.add(jSeparator46);
        jSeparator46.setBounds(40, 130, 50, 20);
        jPanel1.add(jSeparator47);
        jSeparator47.setBounds(40, 140, 50, 20);
        jPanel1.add(jSeparator48);
        jSeparator48.setBounds(40, 150, 50, 20);
        jPanel1.add(jSeparator49);
        jSeparator49.setBounds(40, 160, 50, 20);
        jPanel1.add(jSeparator50);
        jSeparator50.setBounds(40, 170, 50, 20);
        jPanel1.add(jSeparator51);
        jSeparator51.setBounds(40, 180, 50, 20);
        jPanel1.add(jSeparator52);
        jSeparator52.setBounds(40, 190, 50, 20);
        jPanel1.add(jSeparator53);
        jSeparator53.setBounds(40, 200, 50, 20);
        jPanel1.add(jSeparator54);
        jSeparator54.setBounds(40, 210, 50, 20);
        jPanel1.add(jSeparator55);
        jSeparator55.setBounds(40, 220, 50, 20);
        jPanel1.add(jSeparator56);
        jSeparator56.setBounds(40, 230, 50, 20);
        jPanel1.add(jSeparator57);
        jSeparator57.setBounds(40, 240, 50, 20);
        jPanel1.add(jSeparator58);
        jSeparator58.setBounds(40, 250, 50, 20);
        jPanel1.add(jSeparator59);
        jSeparator59.setBounds(40, 260, 50, 20);
        jPanel1.add(jSeparator60);
        jSeparator60.setBounds(40, 270, 50, 20);
        jPanel1.add(jSeparator61);
        jSeparator61.setBounds(40, 280, 50, 20);
        jPanel1.add(jSeparator62);
        jSeparator62.setBounds(40, 290, 50, 20);
        jPanel1.add(jSeparator63);
        jSeparator63.setBounds(40, 300, 50, 20);
        jPanel1.add(jSeparator64);
        jSeparator64.setBounds(40, 310, 50, 20);
        jPanel1.add(jSeparator65);
        jSeparator65.setBounds(40, 320, 50, 20);
        jPanel1.add(jSeparator66);
        jSeparator66.setBounds(40, 330, 50, 20);
        jPanel1.add(jSeparator67);
        jSeparator67.setBounds(40, 340, 50, 20);
        jPanel1.add(jSeparator68);
        jSeparator68.setBounds(40, 350, 50, 20);
        jPanel1.add(jSeparator69);
        jSeparator69.setBounds(40, 350, 50, 20);
        jPanel1.add(jSeparator70);
        jSeparator70.setBounds(40, 360, 50, 20);
        jPanel1.add(jSeparator71);
        jSeparator71.setBounds(40, 370, 50, 20);
        jPanel1.add(jSeparator72);
        jSeparator72.setBounds(40, 380, 50, 20);

        jPanel6.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel6);
        jPanel6.setBounds(700, 0, 10, 470);

        jPanel7.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel7);
        jPanel7.setBounds(0, 0, 10, 470);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoModeloActionPerformed

    private void botaoMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMarcaActionPerformed
        ListaMarca lm = new ListaMarca();
        lm.setVisible(true);
    }//GEN-LAST:event_botaoMarcaActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAutomovel;
    private javax.swing.JButton botaoMarca;
    private javax.swing.JButton botaoModelo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JSeparator jSeparator23;
    private javax.swing.JSeparator jSeparator24;
    private javax.swing.JSeparator jSeparator25;
    private javax.swing.JSeparator jSeparator26;
    private javax.swing.JSeparator jSeparator27;
    private javax.swing.JSeparator jSeparator28;
    private javax.swing.JSeparator jSeparator29;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator30;
    private javax.swing.JSeparator jSeparator31;
    private javax.swing.JSeparator jSeparator32;
    private javax.swing.JSeparator jSeparator33;
    private javax.swing.JSeparator jSeparator34;
    private javax.swing.JSeparator jSeparator35;
    private javax.swing.JSeparator jSeparator36;
    private javax.swing.JSeparator jSeparator37;
    private javax.swing.JSeparator jSeparator38;
    private javax.swing.JSeparator jSeparator39;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator40;
    private javax.swing.JSeparator jSeparator41;
    private javax.swing.JSeparator jSeparator42;
    private javax.swing.JSeparator jSeparator43;
    private javax.swing.JSeparator jSeparator44;
    private javax.swing.JSeparator jSeparator45;
    private javax.swing.JSeparator jSeparator46;
    private javax.swing.JSeparator jSeparator47;
    private javax.swing.JSeparator jSeparator48;
    private javax.swing.JSeparator jSeparator49;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator50;
    private javax.swing.JSeparator jSeparator51;
    private javax.swing.JSeparator jSeparator52;
    private javax.swing.JSeparator jSeparator53;
    private javax.swing.JSeparator jSeparator54;
    private javax.swing.JSeparator jSeparator55;
    private javax.swing.JSeparator jSeparator56;
    private javax.swing.JSeparator jSeparator57;
    private javax.swing.JSeparator jSeparator58;
    private javax.swing.JSeparator jSeparator59;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator60;
    private javax.swing.JSeparator jSeparator61;
    private javax.swing.JSeparator jSeparator62;
    private javax.swing.JSeparator jSeparator63;
    private javax.swing.JSeparator jSeparator64;
    private javax.swing.JSeparator jSeparator65;
    private javax.swing.JSeparator jSeparator66;
    private javax.swing.JSeparator jSeparator67;
    private javax.swing.JSeparator jSeparator68;
    private javax.swing.JSeparator jSeparator69;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator70;
    private javax.swing.JSeparator jSeparator71;
    private javax.swing.JSeparator jSeparator72;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    // End of variables declaration//GEN-END:variables
}
